# -*- coding: utf-8 -*-
"""HanoiTower.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aeOf9tq65-cUIdHhn5Com-fygGdE7h1I
"""

def hanoi_tower(n, start, end, alt):
  if n != 0:
    hanoi_tower(n-1, start, alt, end)
    print(n, start, end)
    hanoi_tower(n-1, alt, end, start)


hanoi_tower(5, "1", "3", "2")